server:
  port: 0
spring:
  application:
    name: product-service-client
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:springCloud;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8801/eureka}
  instance:
    prefer-ip-address: true