server:
  port: 8802
spring:
  application:
    name: front-service-client
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8801/eureka}
  instance:
    prefer-ip-address: true